sales_project:
  outputs:
    dev:
      account: 
      database: SALES_DB
      password: 
      role: FIVETRAN_ROLE
      schema: "{{ env_var('DBT_SCHEMA', 'sales') }}"
      threads: 4
      type: snowflake
      user: 
      warehouse: FIVETRAN_WAREHOUSE
  target: dev